ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'JUDGMENT_CREATED';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'RECOMMENDATION_RECALIBRATED';

ALTER TYPE "AssumptionStatus" ADD VALUE IF NOT EXISTS 'ACTIVE';
ALTER TYPE "AssumptionStatus" ADD VALUE IF NOT EXISTS 'WATCHING';
